config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'static_pages#index'
end

app/models/flickr_api.rb
class FlickrAPI
  def self.flickr
    Flickr
  end

  def self.get_user_photos(user_id)
    user_id && flickr.photos.search(user_id:)
  rescue NameError => _e
    :user_not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :search_photos

  def index
  end

  private

  def search_params
    params.permit(:user_id).compact_blank
  end

  def search_photos
    @photos = FlickrAPI.get_user_photos(search_params[:user_id])
    flash.now.alert = 'User not found.' if @photos == :user_not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def photo_url(photo)
    "https://farm#{photo.farm}.staticflickr.com/#{photo.server}/#{photo.id}_#{photo.secret}_m.jpg"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlickr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/_no_photos.html.erb
<p>User has no photos</p>

app/views/static_pages/_photo.html.erb
<div class="image">
  <div class="image__photo"><%= image_tag photo_url(photo) %></div>
  <h3 class="image__title"><%= photo.title %></h3>
</div>

app/views/static_pages/_user.html.erb
<h2><%= user.name %></h2>

app/views/static_pages/index.html.erb
<%= (content_tag(:div, alert, class: 'alert') ) if alert   %>
<%= form_with url: static_pages_index_path, method: 'get', class: 'search-form' do |form| %>
  <h2 class="search-form__header"><%= form.label :user_id, 'Enter a valid user_id to search a user\'s pictures!' %></h2>
  <%= form.text_field :user_id, value: params[:user_id], class: 'search-form__text-field' %>
  <%= form.submit 'Search', class: 'search-form__button' %>
<% end %>
<% if @photos.is_a?(Array) %>
  <div class="image-list">
    <%= render(partial: 'photo', collection: @photos[0..5]) || render('no_photos') %>
  </div>
<% end %>